### ISSUE TITLE
Biomes settings

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg-client#8]
![image](https://github.com/aresrpg/aresrpg-client/assets/11330271/af761b10-1274-4984-a8e1-fe8435b5cf19)

With the current noise function we have the defaults settings as follows:

```yml
scale: 2004
height: 182
octaves: 7
persistence: 0.46
lacunarity: 2.25
exponentiation: 5.6
```
